name: crawl

on:
  schedule:
    - cron: "50 3 * * *" # runs every day at 03:50 UTC to avoid high loads
  workflow_dispatch:

env:
  HUSKY_SKIP: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: switch to live-data branch
        run: |
          git config --global user.name 'marianfoo'
          git config --global user.email '13335743+marianfoo@users.noreply.github.com'
          git fetch --all
          git checkout live-data
          git pull origin live-data
      - name: rebase from main
        run: |
          git rebase main
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: |
          npm install
      - name: crawl data
        run: |
          npm run build
      - name: Commit/Push build to docs branch
        run: |
          git add data/data.json
          git add data/versions.json
          git commit -m "chore: crawl"
          git push live-data
        continue-on-error: true
